### ISSUE TITLE
Detects QR code coordinates

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#11]
**User Story**
Our user has a paper sketchbook with QR codes in the bottom left corner of each page. The program needs to be able to find the coordinates of the QR code to crop the page successfully.

- **Persona**: Artist using our product
- **Feature**: Detects where the QR code is located
- **Business Value**: Assists in the main feature of our product which is the cropping done by the website. The user will want this because they scan the QR code for ease into the website and for the QR code to also be used to make a high quality crop of the paper they are scanning.

**Tasks**
- [x] Find a library to detect QR codes
- [x] Read through source code to determine how to use the library
- [x] Determine how to find coordinates of qr code in our project
- [x] Write a demo which finds the coordinates on a template page

**Acceptance Criteria**
1. The library is implemented and is functioning for the webpage.
2. We have a good general understanding of how the library works.
3. Code can find QR code on the paper being scanned or uploaded.
4. We have a demo to show how this works and that the feature is functional.
