### ISSUE TITLE
Webapp behavior

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#18]
**User Story**
A user wants to be able to scan their notebook on the go. They want the convenience of having the service as an app on their phone.

- **Persona**: A student who wants to be able to scan on the go
- **Feature**: The product can be made into a web app and added to a phone's home screen
- **Business Value**: We expect our consumers to have a phone and will most likely want to use their phone with our application. This allows them to scan their papers with their phones quickly when they want and wherever they want such as scanning notes or homework.

**Tasks**

- [x] Add functionality in html code for Apple 
- [x] Add functionality in html code for Android
- [x] Add app icon
- [x] Test web app on both devices

**Acceptance Criteria**

- Web app can be added to the home screen on both Apple and Android devices
- App opens our website once tapped on home screen
