### ISSUE TITLE
UI Development

### ISSUE THREAD

**Issue by MWernerS** [COSC481W-2024Winter/augmentedDocScanner#22]
**User Story**
After opening our webapp, a new user needs a well organized page to be able to use the product effectively.

- **Persona:** A new user clicking on our webapp for the first time
- **Feature:** A clean and professional UI
- **Business Value:** Makes the product professional and usable

**Tasks**

- [x] Change PDF Generator page to Template Generator
- [x] Present multiple uploaded images uniformly 
- [x] Generating PDF hides the images that were uploaded, "resets" the page
- [x] Add Template Generator page to navbar
- [x] Make website look more professional.

**Acceptance Criteria**

- PDF Generator page is named to Template Generator
- User can upload multiple images that line up with each other correctly
- Page resets, hides uploaded images once the pdf is generated
- Template Generator is a tab in the navbar, and directs user to the correct page
- Website looks neat and professional for use.
