### ISSUE TITLE
Document Generator codeflow

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#33]
**User story**
As developers, we want a code data flow which we can fill in. We want to set the process in which our input images will be modified into a pdf document.

- **Persona:** Developers who want to write the ADS
- **Feature:** Code data flow materialization
- **Business value:** Defining how the data will flow and be manipulated will allow the developers to work together to write the ADS

**Tasks**
- [ ] There should be a "generate pdf" event handler
- [ ] There should be a function which will eventually accept a list of images, crop them, and return a new list of images
- [ ] The event handler should call the cropping function
- [ ] There should be a function which will eventually accept a list of images and return a pdf object
- [ ] The event handler should call this pdf function
- [ ] There should be a function which downloads a pdf document
- [ ] The event handler should call this function

**Acceptance criteria**
- All of the aforementioned functions are written and callable
