### ISSUE TITLE
PDF Preview Page

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#36]
**User Story**
A user wants to be able to view the pdf that the ADS created before they download it to disk

- **Persona**: An ADS user who wants to preview the pdf
- **Feature**: The user will be able to view the pdf in the browser before downloading it
- **Business Value**: We think users will feel better about using the ADS if it is fully transparent about the results of the tool before it downloads files to the device

**Tasks**

- [x] After clicking the "generate pdf" button, the user is redirected to a new page
- [x] The page the user is redirected to will contain a preview of the pdf
- [x] The page the user is redirected to will have a download button
- [x] The page the user is redirected to will have a back button to return to home

**Acceptance Criteria**

- PDFs are viewable before they are downloaded
- PDFs do not need to be downloaded
- PDFs can be downloaded
