### ISSUE TITLE
Dynamic Template PDF

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#38]
**User Story**
A user wants to be able to scan pages which are not 8.5x11. The user wants to be able to download a blank template which conforms to an arbitrary page size

- **Persona**: An artist with non-standard page size
- **Feature**: Blank printable template pages can be generated for any page size
- **Business Value**: Our product will be able to cater to more users when they aren't forced to use the standard page size

**Tasks**
- [x] A function is written which generates a QR code given a link
- [x] QR code will contain page size information
- [x] Metadata will be contained as url params
- [x] There are inputs for page size and qr code coords on the template generator

**Acceptance Criteria**
- User can generate different size PDFs
- User can place qr code in different locations on PDF
