### ISSUE TITLE
Improve UI Look

### ISSUE THREAD

**Issue by bsayre2** [COSC481W-2024Winter/augmentedDocScanner#39]
**User Story**
User is visiting our website and wants to feel as if it is professional and trustworthy.

- **Persona:** A student wanting to use our app for the first time
- **Feature:** UI is professional looking and has no bugs
- **Business Value:** User's are more likely to use our app

**Tasks**

- [ ] Improve the look of the uploaded image list
- [ ] Fix navbar on mobile, no condensed tabs!!
- [ ] Make sure mobile matches up with desktop app
- [ ] Improve the look of the UI including camera feature, button styles, paper background, etc.

**Acceptance Criteria**

- Page looks professional according to all members of the group
- Navbar displays the same on mobile as on desktop
- All features of the website work no matter the order in which they are executed
