### ISSUE TITLE
Image keystoning

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#48]
A user would like to quickly scan their stack of documents via uploading photos to the ADS.  The user quickly takes a photo of each page, but they are unable to hold their camera perfectly level, so the images are skewed incorrectly, and some are even rotated incorrectly

1. Persona:  A user who needs to quickly scan many documents.
2. Feature:  Automatic keystoning and rotation to fix skew
3. Business Value:  A user can create .pdfs quickly without having to manually line up the camera with the document.

**Tasks**

- [ ] Read QR code orientation
- [ ] Straighten the skew
- [ ] Rotate image correctly

**Acceptance Criteria**

- This should be an improvement on the existing crop function
- There should be a new list of images that only includes the keystoned/cropped/rotated pages
