### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#8]
**User Story**
A new user has visited our website, and clicked around a little bit. They are still confused on how exactly to use the product. They decide to click on the "help" link, and are sent to a new page.

- **Persona**: A new user using our product for the first time
- **Feature**: Help page with description of how to use our product
- **Business Value**: Allows more users to use our product

**Tasks:**
- [x] build Help page
- [x] add Help button to main page
- [x] link Help button to Help page
- [x] link back button to main page

**Acceptance Criteria:**
1.  Help button links to help page
2. Help page displays all information a user needs to use ADS
3. Return button links back to main page
