### ISSUE TITLE
Create main webpage

### ISSUE THREAD

**Issue by bteastman** [COSC481W-2024Winter/augmentedDocScanner#9]
****User Story****
A new user needed a new and more efficient PDF scanner for their sketch book. They searched and found our website. They need a landing page after clicking on the link.

- **Persona**: A new user
- **Feature:** Website's landing page, with buttons to upload pictures, take pictures, and create pdfs (buttons view only). It also has links to the help and about buttons.
- **Business Plan**: Allows user's to use our scanner

**Tasks**
- [x] Make functional and nice looking style.
- [x] Working Buttons.
- [x] Take pictures and upload images.
- [x] Working links to About and Help pages.

**Acceptance Criteria**
1. The Main Webpage looks exceptionally nice.
2. The buttons and links all work.
3. Features are functional and do their assigned task such as "Take Picture" button takes a picture.
